[package]
name = "p0f"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
failure = "0.1"
lazy_static = "1.3"
derive_more = "0.14"
nom = "4.2"

[dev-dependencies]
pretty_env_logger = "0.3"
